(function () {
  'use strict';
  const LABEL={atencao_prioritaria:'Atenção prioritária',atencao:'Atenção',demais_areas:'Demais áreas',outro:'Outro',expansao_urbana:'Expansão urbana',consolidacao:'Consolidação urbana',vulnerabilidade:'Vulnerabilidade ou risco',infraestrutura:'Carência de infraestrutura',pressao_ambiental:'Pressão ambiental'};
  const CLASS_KEYS=['atencao_prioritaria','atencao','demais_areas','outro'];
  const COLOR={atencao_prioritaria:'#d7191c',atencao:'#f28e2b',demais_areas:'#2a9d5b',outro:'#6b7280',expansao_urbana:'#7c3aed',consolidacao:'#7c3aed',vulnerabilidade:'#7c3aed',infraestrutura:'#7c3aed',pressao_ambiental:'#7c3aed'};
  const ACTION={confirm:'Confirmou o modelo',reclassify:'Viu diferente',free:'Desenho livre'};
  const LAB_MODE=location.pathname.replace(/\/$/,'')==='/percepcao-grade'||new URLSearchParams(location.search).get('percepcao')==='grade';
  if(LAB_MODE)document.body.classList.add('fcu-grid-lab');
  let map,db,layers=L.layerGroup(),editHandles=L.layerGroup(),gridLayer=L.layerGroup(),items=[],layerById=new Map(),gridCells=new Map(),drawing=false,dragging=false,geometryEditing=false,gridMode=false,points=[],originalPoints=[],selectedVertex=-1,drawingZoom=13,draftLayer,draft,editingId,editingRecord,lastCell='';
  const filters={visible:true,classes:new Set(Object.keys(LABEL)),actions:new Set(Object.keys(ACTION))};
  window.PreditorPerception={isDrawing:()=>drawing||geometryEditing};
  const $=s=>document.querySelector(s), user=()=>window.PreditorAuth&&window.PreditorAuth.user, app=()=>window.__PREDITOR_APP__||{}, sample=()=>app().selectedSample||null;
  const esc=v=>String(v==null?'':v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  function status(t,e,target='#fcu-perception-status'){const n=$(target);if(n){n.textContent=t||'';n.classList.toggle('is-error',!!e);}}
  function open(){ $('#fcu-perception-panel').classList.add('is-open');$('#fcu-perception-shade').classList.add('is-open');renderContext(); }
  function close(){ $('#fcu-perception-panel').classList.remove('is-open');$('#fcu-perception-shade').classList.remove('is-open'); }
  function classOf(s){let k=null;try{const fn=window.PreditorModel&&window.PreditorModel.samplePriorityKey;if(typeof fn==='function')k=fn(s);}catch(_){ }return {priority:'atencao_prioritaria',attention:'atencao',other:'demais_areas'}[k]||null;}
  function cellGeometry(s){const lat=Number(s.lat),lng=Number(s.lng),half=Number(s.res_m||50)/2;if(!Number.isFinite(lat)||!Number.isFinite(lng))return null;const dy=half/111320,dx=half/(111320*Math.max(.2,Math.cos(lat*Math.PI/180)));return {type:'Polygon',coordinates:[[[lng-dx,lat-dy],[lng+dx,lat-dy],[lng+dx,lat+dy],[lng-dx,lat+dy],[lng-dx,lat-dy]]]};}
  function snapshot(s){return {captured_at:new Date().toISOString(),cell_id:String(s.id||''),area_id:s.scope||s.a||null,model_class:classOf(s),probability:Number.isFinite(Number(s.proba))?Number(s.proba):null,ranking_candidato:Number.isFinite(Number(s.ranking_candidato))?Number(s.ranking_candidato):null,ranking_total:Number.isFinite(Number(s.ranking_total))?Number(s.ranking_total):null,target:Number.isFinite(Number(s.target))?Number(s.target):null,municipio:s.municipio||null,scenario:s.local_scenario||s.winner_scenario||null,resolution_m:Number(s.res_m||50)};}
  function toPoints(g){const r=g&&g.coordinates&&g.coordinates[0];return (r||[]).slice(0,-1).map(p=>[p[1],p[0]]);}
  function toGeometry(){const r=points.map(p=>[p[1],p[0]]);r.push(r[0].slice());return {type:'Polygon',coordinates:[r]};}
  function segmentsCross(a,b,c,d){const turn=(p,q,r)=>(q[1]-p[1])*(r[0]-p[0])-(q[0]-p[0])*(r[1]-p[1]);return turn(a,b,c)*turn(a,b,d)<0&&turn(c,d,a)*turn(c,d,b)<0;}
  function selfIntersects(list){for(let i=0;i<list.length;i++)for(let j=i+1;j<list.length;j++){if(j===i||j===(i+1)%list.length||i===(j+1)%list.length)continue;if(segmentsCross(list[i],list[(i+1)%list.length],list[j],list[(j+1)%list.length]))return true;}return false;}
  function convexHull(list){const sorted=list.map(p=>p.slice()).sort((a,b)=>a[1]-b[1]||a[0]-b[0]),cross=(o,a,b)=>(a[1]-o[1])*(b[0]-o[0])-(a[0]-o[0])*(b[1]-o[1]),lower=[],upper=[];sorted.forEach(p=>{while(lower.length>=2&&cross(lower[lower.length-2],lower[lower.length-1],p)<=0)lower.pop();lower.push(p);});sorted.slice().reverse().forEach(p=>{while(upper.length>=2&&cross(upper[upper.length-2],upper[upper.length-1],p)<=0)upper.pop();upper.push(p);});return lower.slice(0,-1).concat(upper.slice(0,-1));}
  function drawingDetail(zoom=drawingZoom){const z=Math.max(8,Math.min(19,Number(zoom)||13));return {samplePx:Math.round(34-(z-8)*1.5),simplifyPx:Math.round(28-(z-8)*1.35),maxPoints:Math.round(8+(z-8)*1.45)};}
  function normalizePoints(list,zoom=drawingZoom){const detail=drawingDetail(zoom),project=p=>map.project(L.latLng(p),zoom),unproject=p=>{const ll=map.unproject(p,zoom);return[ll.lat,ll.lng];};let clean=list.filter((p,i)=>i===0||project(p).distanceTo(project(list[i-1]))>=Math.max(8,detail.samplePx/2));if(clean.length>3)clean=L.LineUtil.simplify(clean.map(project),detail.simplifyPx).map(unproject);if(clean.length>detail.maxPoints){const step=clean.length/detail.maxPoints;clean=Array.from({length:detail.maxPoints},(_,i)=>clean[Math.floor(i*step)]);}if(selfIntersects(clean))clean=convexHull(clean);return clean;}
  function gridGeometry(){const corners=[];gridCells.forEach(v=>cellGeometry(v).coordinates[0].slice(0,-1).forEach(p=>corners.push([p[1],p[0]])));const hull=convexHull(corners),ring=hull.map(p=>[p[1],p[0]]);ring.push(ring[0].slice());return {type:'Polygon',coordinates:[ring]};}
  function renderGrid(){gridLayer.clearLayers();gridCells.forEach(s=>L.geoJSON(cellGeometry(s),{style:{color:'#6d28d9',weight:2,fillColor:'#8b5cf6',fillOpacity:.38}}).addTo(gridLayer));if(!map.hasLayer(gridLayer))gridLayer.addTo(map);const count=$('#fcu-grid-count'),save=$('#fcu-grid-save');if(count)count.textContent=gridCells.size?`${gridCells.size} ${gridCells.size===1?'célula selecionada':'células selecionadas'}`:'Nenhuma célula selecionada';if(save)save.disabled=!gridCells.size;}
  function addGridCell(){if(!requireLogin())return;const s=sample(),g=cellGeometry(s);if(!s||!g)return status('Clique primeiro em uma célula do mapa.',true);gridCells.set(String(s.id),JSON.parse(JSON.stringify(s)));renderGrid();status('Célula adicionada. Selecione outra no mapa ou salve.');}
  function removeGridCell(){const s=sample();if(s)gridCells.delete(String(s.id));renderGrid();status(gridCells.size?'Célula removida.':'Seleção limpa.');}
  function clearGrid(){gridCells.clear();renderGrid();status('Seleção limpa.');}
  function finishGrid(){if(!gridCells.size)return;const cells=[...gridCells.values()],first=cells[0];draft={id:crypto.randomUUID(),target_kind:'polygon',action_type:'free',cell_id:cells.length===1?String(first.id):null,model_class:null,model_probability:null,model_snapshot:{captured_at:new Date().toISOString(),area_id:areaId(),selection_mode:'grid',grid_cell_ids:cells.map(s=>String(s.id)),grid_cells:cells.map(s=>({snapshot:snapshot(s),geometry:cellGeometry(s)}))},geometry_source:'user_polygon',geometry:gridGeometry()};points=toPoints(draft.geometry);gridMode=true;editingId=null;showForm(null);}
  function buildMapModeControls(){if($('.fcu-map-mode-control'))return;const box=document.createElement('div');box.className='fcu-map-mode-control';box.innerHTML='<div><button type="button" data-base="street" class="is-active">Ruas</button><button type="button" data-base="satellite">Satélite</button></div><div><button type="button" data-view="2d" class="is-active">2D</button><button type="button" data-view="3d">3D</button></div>';document.querySelector('.local-map-panel').appendChild(box);let street=null;map.eachLayer(l=>{if(l instanceof L.TileLayer&&l!==app().satelliteLayer&&!street)street=l;});box.querySelector('[data-base="street"]').onclick=()=>{if(app().satelliteLayer&&map.hasLayer(app().satelliteLayer))map.removeLayer(app().satelliteLayer);if(street&&!map.hasLayer(street))street.addTo(map);box.querySelectorAll('[data-base]').forEach(b=>b.classList.toggle('is-active',b.dataset.base==='street'));};box.querySelector('[data-base="satellite"]').onclick=()=>{if(street&&map.hasLayer(street))map.removeLayer(street);if(app().satelliteLayer&&!map.hasLayer(app().satelliteLayer))app().satelliteLayer.addTo(map);box.querySelectorAll('[data-base]').forEach(b=>b.classList.toggle('is-active',b.dataset.base==='satellite'));};box.querySelector('[data-view="3d"]').onclick=()=>{const s=sample(),c=map.getCenter(),lat=Number(s&&s.lat)||c.lat,lng=Number(s&&s.lng)||c.lng;window.open(`3d.html?lat=${lat}&lng=${lng}&zoom=${Math.max(15,map.getZoom())}${s&&s.id?'&cell='+encodeURIComponent(s.id):''}`,'_blank','noopener');};}
  function drawingId(id){return id?'#'+String(id).split('-')[0].toUpperCase():'#NOVO';}
  function areaId(){const s=sample();if(s&&(s.scope||s.a))return String(s.scope||s.a);const a=$('#area-select');return a&&a.value||null;}
  function requireLogin(){if(user())return true;close();const b=$('#fcu-auth-button');if(b)b.click();return false;}

  function build(){const host=document.querySelector('.local-map-panel');if(!host||$('.fcu-perception-button'))return false;if(getComputedStyle(host).position==='static')host.style.position='relative';
    host.insertAdjacentHTML('beforeend','<div class="fcu-perception-map-tools"><button class="fcu-perception-button" type="button">＋ Minha percepção</button></div>');
    document.body.insertAdjacentHTML('beforeend',`<div class="fcu-perception-shade" id="fcu-perception-shade"></div><aside class="fcu-perception-panel" id="fcu-perception-panel" aria-label="Percepções territoriais">
    <div class="fcu-perception-head"><div><h2>Minha percepção</h2><p>Compare sua leitura do território com o resultado do Preditor.</p></div><button class="fcu-perception-close" type="button" aria-label="Fechar">×</button></div>
    <div id="fcu-perception-start"><section class="fcu-context-card" id="fcu-context-card"></section>${LAB_MODE?'<section class="fcu-grid-picker"><strong>Selecionar pela grade</strong><p>Clique em uma célula do mapa e use os botões abaixo. As células ficam reunidas em uma percepção.</p><div><button id="fcu-grid-add" type="button">＋ Adicionar</button><button id="fcu-grid-remove" type="button">− Remover</button><button id="fcu-grid-clear" type="button">Limpar</button><button id="fcu-grid-save" type="button" disabled>✓ Salvar</button></div><small id="fcu-grid-count">Nenhuma célula selecionada</small></section>':''}<button class="fcu-perception-secondary fcu-free-button" id="fcu-start-drawing" type="button">✎ Desenhar área livre</button><p class="fcu-help">Você também pode desenhar um contorno livre e ajustar seus pontos.</p><p class="fcu-perception-status" id="fcu-perception-status"></p>
    <details class="fcu-filter-box" open><summary>Filtrar camada de percepções</summary><label class="fcu-filter-master"><input data-layer-visible type="checkbox" checked> Exibir no mapa</label><div class="fcu-filter-grid">${CLASS_KEYS.map(v=>`<label><input data-class-filter="${v}" type="checkbox" checked><i style="--fcu-color:${COLOR[v]}"></i>${LABEL[v]}</label>`).join('')}</div><div class="fcu-filter-grid fcu-action-filters">${Object.entries(ACTION).map(([v,l])=>`<label><input data-action-filter="${v}" type="checkbox" checked>${l}</label>`).join('')}</div></details>
    <div class="fcu-perception-tabs"><button class="is-active" type="button" data-tab="active">Minhas percepções</button><button type="button" data-tab="history">Lixeira</button></div><div id="fcu-perception-list"></div><div id="fcu-perception-history" hidden></div></div>
    <form class="fcu-perception-form" id="fcu-perception-form" hidden><button class="fcu-form-back" id="fcu-cancel-form" type="button">← Voltar</button><div class="fcu-form-summary" id="fcu-form-summary"></div><fieldset id="fcu-class-field"><legend>Como você classifica esta área?</legend>${CLASS_KEYS.map(v=>`<label class="fcu-choice fcu-choice-${v}"><input type="radio" name="classification" value="${v}" required><span class="fcu-choice-mark">✓</span><span>${LABEL[v]}</span></label>`).join('')}</fieldset>
    <label class="fcu-check fcu-field-check"><input type="checkbox" name="field_validation"> Houve validação prática ou visita em campo para esta percepção.</label><label class="fcu-field-date" hidden>Data da visita <span>(opcional)</span><input type="date" name="field_visit_date"></label>
    <label>Comentário breve <span>(opcional)</span></label><textarea name="description" maxlength="800" rows="3" placeholder="O que foi observado?"></textarea><details class="fcu-extra-details"><summary>＋ Mais detalhes (opcional)</summary><label>Título</label><input name="title" type="text" maxlength="120" placeholder="Ex.: visita de campo"><label>Força da percepção</label><select name="intensity"><option value="3">Média</option><option value="1">Muito baixa</option><option value="2">Baixa</option><option value="4">Alta</option><option value="5">Muito alta</option></select><label>Quando isso é percebido?</label><select name="time_reference"><option value="atual">Atualmente</option><option value="recente">Nos últimos anos</option><option value="historica">É histórico</option><option value="nao_sei">Não sei informar</option></select><label>Quanto conhece a área?</label><select name="confidence"><option value="media">Razoavelmente</option><option value="baixa">Pouco</option><option value="alta">Muito bem</option></select><fieldset class="fcu-knowledge"><legend>Como conhece esta área?</legend><label><input type="checkbox" name="knowledge_source" value="visita_campo"> Visita ou atividade em campo</label><label><input type="checkbox" name="knowledge_source" value="mora_trabalha"> Moro ou trabalho na área</label><label><input type="checkbox" name="knowledge_source" value="pesquisa_tecnica"> Pesquisa, dados ou trabalho técnico</label><label><input type="checkbox" name="knowledge_source" value="relatos"> Relatos de moradores ou parceiros</label><label><input type="checkbox" name="knowledge_source" value="outro"> Outra forma</label></fieldset></details><button class="fcu-perception-primary" type="submit">Salvar percepção</button><p class="fcu-perception-status" id="fcu-form-status"></p></form></aside>`);
    $('.fcu-perception-button').onclick=()=>{open();load();};$('.fcu-perception-close').onclick=close;$('#fcu-perception-shade').onclick=close;$('#fcu-start-drawing').onclick=startDrawing;$('#fcu-cancel-form').onclick=reset;$('#fcu-perception-form').onsubmit=save;if(LAB_MODE){$('#fcu-grid-add').onclick=addGridCell;$('#fcu-grid-remove').onclick=removeGridCell;$('#fcu-grid-clear').onclick=clearGrid;$('#fcu-grid-save').onclick=finishGrid;buildMapModeControls();}
    document.querySelectorAll('[data-layer-visible]').forEach(n=>n.onchange=e=>setVisible(e.target.checked));
    document.querySelectorAll('[data-class-filter]').forEach(n=>n.onchange=e=>{e.target.checked?filters.classes.add(e.target.dataset.classFilter):filters.classes.delete(e.target.dataset.classFilter);renderLayers();});
    document.querySelectorAll('[data-action-filter]').forEach(n=>n.onchange=e=>{e.target.checked?filters.actions.add(e.target.dataset.actionFilter):filters.actions.delete(e.target.dataset.actionFilter);renderLayers();});
    document.querySelectorAll('[data-tab]').forEach(n=>n.onclick=()=>showTab(n.dataset.tab));const field=fcuFieldCheckbox();field.onchange=()=>{$('.fcu-field-date').hidden=!field.checked;if(field.checked){const source=$('[name="knowledge_source"][value="visita_campo"]');source.checked=true;}};return true;}
  function fcuFieldCheckbox(){return $('#fcu-perception-form [name="field_validation"]');}
  function renderLegendControl(){const body=document.querySelector('.all-points-control .legend-body'),old=document.querySelector('.fcu-legend-perceptions');if(!body||!user()){if(old)old.remove();return;}if(old){const button=old.querySelector('button');button.classList.toggle('is-off',!filters.visible);button.setAttribute('aria-checked',String(filters.visible));return;}const group=document.createElement('div');group.className='fcu-legend-perceptions';group.innerHTML=`<div class="fcu-legend-title">Camada do participante</div><button type="button" role="switch" aria-checked="${filters.visible}"><span class="fcu-legend-swatch"></span><span>Minhas percepções</span><i></i></button>`;group.querySelector('button').onclick=e=>{e.preventDefault();e.stopPropagation();setVisible(!filters.visible);};body.appendChild(group);}
  function setVisible(v){filters.visible=v;const top=$('#fcu-layer-toggle');if(top)top.checked=v;document.querySelectorAll('[data-layer-visible]').forEach(n=>n.checked=v);if(v&&!map.hasLayer(layers))layers.addTo(map);if(!v&&map.hasLayer(layers))map.removeLayer(layers);renderLegendControl();}
  function renderContext(){const h=$('#fcu-context-card'),s=sample(),k=classOf(s);if(!h)return;if(!s||!k){h.innerHTML='<h3>Avalie um resultado do mapa</h3><p>Clique primeiro em uma célula do Preditor. Depois confirme o resultado ou indique outra classificação.</p>';lastCell='';return;}lastCell=String(s.id||'');const p=Number.isFinite(Number(s.proba))?(Number(s.proba)*100).toFixed(1)+'%':'—';h.innerHTML=`<span class="fcu-context-eyebrow">Célula selecionada</span><h3>${esc(s.id)}</h3><div class="fcu-model-result"><i style="--fcu-color:${COLOR[k]}"></i><span>Preditor: <strong>${LABEL[k]}</strong><small>Probabilidade ${p}</small></span></div><div class="fcu-context-actions"><button type="button" data-confirm>✓ Concordo com o resultado</button><button type="button" data-different>Vejo esta área diferente</button></div><p class="fcu-help">Sua opinião é uma camada separada e não altera o resultado original.</p>`;h.querySelector('[data-confirm]').onclick=()=>beginCell('confirm');h.querySelector('[data-different]').onclick=()=>beginCell('reclassify');}
  function beginCell(action){if(!requireLogin())return;const s=sample(),k=classOf(s),g=cellGeometry(s);if(!s||!k||!g)return status('Selecione novamente uma célula válida.',true);draft={id:crypto.randomUUID(),target_kind:'cell',action_type:action,cell_id:String(s.id),model_class:k,model_probability:Number.isFinite(Number(s.proba))?Number(s.proba):null,model_snapshot:snapshot(s),geometry_source:'model_cell',geometry:g};points=toPoints(g);editingId=null;showForm(action==='confirm'?k:null);}
  function showForm(selected,record){const f=$('#fcu-perception-form');$('#fcu-perception-start').hidden=true;f.hidden=false;f.reset();const model=draft.model_class&&LABEL[draft.model_class],isGrid=draft.model_snapshot&&draft.model_snapshot.selection_mode==='grid';$('#fcu-form-summary').innerHTML=draft.action_type==='confirm'?`<strong>✓ Confirmar resultado</strong><span>Preditor: ${model}</span>`:draft.action_type==='reclassify'?`<strong>Indicar uma leitura diferente</strong><span>Preditor: ${model}</span>`:isGrid?`<strong>Classificar seleção da grade</strong><span>${draft.model_snapshot.grid_cell_ids.length} célula(s)</span>`:'<strong>Classificar a área desenhada</strong><span>Desenho livre</span>';
    if(record){f.elements.title.value=record.title||'';f.elements.intensity.value=record.intensity||3;f.elements.time_reference.value=record.time_reference||'atual';f.elements.confidence.value=record.confidence||'media';f.elements.description.value=record.description||'';(record.knowledge_sources||[]).forEach(value=>{const n=f.querySelector(`[name="knowledge_source"][value="${value}"]`);if(n)n.checked=true;});f.elements.field_validation.checked=!!record.field_validation;f.elements.field_visit_date.value=record.field_visit_date||'';}else f.elements.title.value=draft.action_type==='confirm'?`Confirmo ${model}`:'';
    $('.fcu-field-date').hidden=!f.elements.field_validation.checked;
    $('#fcu-form-summary').insertAdjacentHTML('afterbegin',`<small class="fcu-drawing-id">Desenho ${drawingId(editingId||draft.id)}</small>`);const choice=f.querySelector(`[name="classification"][value="${selected||(record&&record.perceived_class)||''}"]`);if(choice)choice.checked=true;const locked=draft.action_type==='confirm';f.querySelectorAll('[name="classification"]').forEach(n=>n.disabled=locked);$('#fcu-class-field').classList.toggle('is-locked',locked);open();status('',false,'#fcu-form-status');}
  function startDrawing(){if(!requireLogin())return;close();drawing=true;dragging=false;drawingZoom=map.getZoom();points=[];draft=null;editingId=null;if(draftLayer)map.removeLayer(draftLayer);draftLayer=null;document.body.insertAdjacentHTML('beforeend','<div class="fcu-perception-drawnote" id="fcu-perception-drawnote"><strong>Desenhe a área percebida</strong><span id="fcu-point-count">Arraste o contorno; o detalhe se adapta ao zoom</span><div><button id="fcu-undo" type="button" disabled>↶ Desfazer</button><button id="fcu-finish" type="button" disabled>✓ Concluir</button><button id="fcu-cancel" type="button">Cancelar</button></div></div>');$('#fcu-undo').onclick=()=>{points.pop();redraw();};$('#fcu-finish').onclick=finish;$('#fcu-cancel').onclick=()=>{reset();open();};map.getContainer().style.cursor='crosshair';}
  function redraw(){if(draftLayer)map.removeLayer(draftLayer);draftLayer=points.length>=3?L.polygon(points,{color:'#7c3aed',weight:3,fillOpacity:.18}).addTo(map):points.length?L.polyline(points,{color:'#7c3aed',weight:3}).addTo(map):null;const c=$('#fcu-point-count');if(c)c.textContent=`${points.length} ${points.length===1?'ponto':'pontos'} marcados`;if($('#fcu-undo'))$('#fcu-undo').disabled=!points.length;if($('#fcu-finish'))$('#fcu-finish').disabled=points.length<3;}
  function add(latlng){const p=[latlng.lat,latlng.lng],prev=points[points.length-1],detail=drawingDetail();if(prev&&map.project(L.latLng(prev),drawingZoom).distanceTo(map.project(latlng,drawingZoom))<detail.samplePx)return;points.push(p);redraw();}
  function mapClick(e){if(drawing&&!dragging)add(e.latlng);}function pointerDown(e){if(!drawing||e.button!==0||e.target.closest('.leaflet-control'))return;dragging=true;map.dragging.disable();add(map.mouseEventToLatLng(e));}function pointerMove(e){if(drawing&&dragging)add(map.mouseEventToLatLng(e));}function pointerUp(e){if(!drawing||!dragging)return;add(map.mouseEventToLatLng(e));dragging=false;map.dragging.enable();if(points.length>=5)finish(e);}
  function finish(e){if(e){e.preventDefault();e.stopPropagation();}points=normalizePoints(points);if(points.length<3)return;drawing=false;dragging=false;map.dragging.enable();map.getContainer().style.cursor='';const n=$('#fcu-perception-drawnote');if(n)n.remove();draft={id:crypto.randomUUID(),target_kind:'polygon',action_type:'free',cell_id:null,model_class:null,model_probability:null,model_snapshot:{captured_at:new Date().toISOString(),area_id:areaId()},geometry_source:'user_polygon',geometry:toGeometry()};beginGeometryEdit(null,true);}
  function reset(){drawing=false;dragging=false;geometryEditing=false;gridMode=false;points=[];originalPoints=[];selectedVertex=-1;draft=null;editingId=null;editingRecord=null;gridCells.clear();gridLayer.clearLayers();if(map){map.dragging.enable();map.getContainer().style.cursor='';}editHandles.clearLayers();if(draftLayer){map.removeLayer(draftLayer);draftLayer=null;}const n=$('#fcu-perception-drawnote');if(n)n.remove();const f=$('#fcu-perception-form');if(f){f.reset();f.hidden=true;}if($('#fcu-perception-start'))$('#fcu-perception-start').hidden=false;status('');renderGrid();renderContext();}
  async function save(e){e.preventDefault();if(!requireLogin()||!draft)return;const f=e.currentTarget,v=new FormData(f),perceived=draft.action_type==='confirm'?draft.model_class:String(v.get('classification')||''),sources=v.getAll('knowledge_source').map(String),fieldValidation=v.get('field_validation')==='on';if(!perceived)return status('Escolha uma classificação.',true,'#fcu-form-status');if(!sources.length)sources.push(fieldValidation?'visita_campo':'nao_informado');if(draft.action_type==='reclassify'&&perceived===draft.model_class)return status('Escolha uma classe diferente do resultado do Preditor.',true,'#fcu-form-status');const autoTitle=`Percepção ${new Date().toLocaleDateString('pt-BR')}`,payload={user_id:user().id,title:String(v.get('title')||'').trim()||autoTitle,perception_types:[perceived],perceived_class:perceived,intensity:Number(v.get('intensity')||3),time_reference:String(v.get('time_reference')||'atual'),confidence:String(v.get('confidence')||'media'),knowledge_sources:sources,field_validation:fieldValidation,field_visit_date:fieldValidation&&v.get('field_visit_date')?String(v.get('field_visit_date')):null,description:String(v.get('description')||'').trim(),area_id:areaId(),geometry:draft.geometry,status:'submitted',target_kind:draft.target_kind,action_type:draft.action_type,cell_id:draft.cell_id,model_class:draft.model_class,model_probability:draft.model_probability,model_snapshot:draft.model_snapshot||{},geometry_source:draft.geometry_source};if(!editingId)payload.id=draft.id;const id=editingId,b=f.querySelector('[type="submit"]');b.disabled=true;status('Salvando...',false,'#fcu-form-status');const r=id?await db.from('fcu_perceptions').update(payload).eq('id',id):await db.from('fcu_perceptions').insert(payload);b.disabled=false;if(r.error)return status('Não foi possível salvar. O contorno será ajustado automaticamente; tente novamente.',true,'#fcu-form-status');reset();open();status(id?'Alteração salva; a versão anterior foi preservada.':`Desenho ${drawingId(payload.id)} salvo na sua camada.`);await load();}
  async function archive(id){if(!confirm('Remover esta percepção do mapa e enviá-la para a Lixeira?'))return;const r=await db.from('fcu_perceptions').update({status:'archived'}).eq('id',id);if(r.error)return status('Não foi possível excluir.',true);status('Percepção removida do mapa. Ela pode ser restaurada.');load();}
  async function restore(id){const r=await db.from('fcu_perceptions').update({status:'submitted'}).eq('id',id);if(r.error)return status('Não foi possível restaurar.',true);showTab('active');status('Percepção restaurada no mapa.');load();}
  function editorIcon(kind,selected=false){return L.divIcon({className:'fcu-edit-marker-wrap',html:`<span class="fcu-edit-marker ${kind}${selected?' is-selected':''}"></span>`,iconSize:[24,24],iconAnchor:[12,12]});}
  function polygonCenter(){const sum=points.reduce((a,p)=>[a[0]+p[0],a[1]+p[1]],[0,0]);return [sum[0]/points.length,sum[1]/points.length];}
  function renderEditor(){editHandles.clearLayers();if(draftLayer)map.removeLayer(draftLayer);draftLayer=L.polygon(points,{color:'#0957d0',weight:4,fillColor:'#3b82f6',fillOpacity:.18}).addTo(map);points.forEach((p,index)=>{const marker=L.marker(p,{draggable:true,icon:editorIcon('vertex',selectedVertex===index),zIndexOffset:1200}).addTo(editHandles);marker.on('click',e=>{L.DomEvent.stopPropagation(e);selectedVertex=index;renderEditor();});marker.on('drag',e=>{points[index]=[e.latlng.lat,e.latlng.lng];draftLayer.setLatLngs(points);});marker.on('dragend',()=>renderEditor());});const center=polygonCenter(),base=points.map(p=>p.slice());const mover=L.marker(center,{draggable:true,icon:editorIcon('center'),zIndexOffset:1300}).addTo(editHandles);mover.bindTooltip('Arraste para mover toda a área',{direction:'top'});mover.on('drag',e=>{const ll=e.target.getLatLng(),dy=ll.lat-center[0],dx=ll.lng-center[1];points=base.map(p=>[p[0]+dy,p[1]+dx]);draftLayer.setLatLngs(points);editHandles.eachLayer(layer=>{if(layer!==mover&&layer.dragging)layer.setOpacity(0);});});mover.on('dragend',()=>renderEditor());const remove=$('#fcu-remove-vertex');if(remove)remove.disabled=selectedVertex<0||points.length<=3;}
  function closeEditor(){geometryEditing=false;selectedVertex=-1;editHandles.clearLayers();if(draftLayer){map.removeLayer(draftLayer);draftLayer=null;}const bar=$('#fcu-geometry-toolbar');if(bar)bar.remove();}
  function beginGeometryEdit(record,isNew=false){if(!requireLogin())return;close();geometryEditing=true;editingRecord=record||null;editingId=record?record.id:null;if(record){draft={id:record.id,target_kind:record.target_kind||'polygon',action_type:record.action_type||'free',cell_id:record.cell_id,model_class:record.model_class,model_probability:record.model_probability,model_snapshot:record.model_snapshot||{},geometry_source:record.geometry_source||'user_polygon',geometry:record.geometry};drawingZoom=map.getZoom();points=normalizePoints(toPoints(record.geometry),drawingZoom);}originalPoints=points.map(p=>p.slice());document.body.insertAdjacentHTML('beforeend',`<div class="fcu-geometry-toolbar" id="fcu-geometry-toolbar"><div><strong>Desenho ${drawingId(record?record.id:draft.id)}</strong><span>Arraste os pontos de inflexão; o ponto central move tudo.</span></div><div>${LAB_MODE?'<button id="fcu-add-vertex" type="button">＋ Adicionar ponto</button>':''}<button id="fcu-remove-vertex" type="button" disabled>− Excluir ponto</button><button id="fcu-editor-cancel" type="button">Cancelar</button>${record?'<button id="fcu-editor-delete" type="button" class="is-danger">Excluir desenho</button>':''}<button id="fcu-editor-ok" type="button" class="is-primary">✓ OK</button></div></div>`);if(LAB_MODE)$('#fcu-add-vertex').onclick=()=>{let best=0,bestDistance=-1;points.forEach((p,i)=>{const n=points[(i+1)%points.length],d=map.distance(p,n);if(d>bestDistance){best=i;bestDistance=d;}});const a=points[best],b=points[(best+1)%points.length];points.splice(best+1,0,[(a[0]+b[0])/2,(a[1]+b[1])/2]);selectedVertex=best+1;renderEditor();};$('#fcu-remove-vertex').onclick=()=>{if(selectedVertex>=0&&points.length>3){points.splice(selectedVertex,1);selectedVertex=-1;renderEditor();}};$('#fcu-editor-cancel').onclick=()=>{points=originalPoints.map(p=>p.slice());closeEditor();reset();if(record){open();load();}};if(record)$('#fcu-editor-delete').onclick=async()=>{closeEditor();reset();open();await archive(record.id);};$('#fcu-editor-ok').onclick=async()=>{points=normalizePoints(points,drawingZoom);draft.geometry=toGeometry();if(isNew){closeEditor();showForm(null);return;}const button=$('#fcu-editor-ok');button.disabled=true;button.textContent='Salvando…';const result=await db.from('fcu_perceptions').update({geometry:draft.geometry}).eq('id',record.id);if(result.error){button.disabled=false;button.textContent='✓ OK';return alert('Não foi possível salvar o contorno: '+result.error.message);}closeEditor();reset();open();status(`Desenho ${drawingId(record.id)} atualizado; a forma anterior foi preservada.`);await load();};editHandles.addTo(map);renderEditor();map.fitBounds(draftLayer.getBounds(),{padding:[50,50]});}
  function edit(r){editingId=r.id;draft={target_kind:r.target_kind||'polygon',action_type:r.action_type||'free',cell_id:r.cell_id,model_class:r.model_class,model_probability:r.model_probability,model_snapshot:r.model_snapshot||{},geometry_source:r.geometry_source||'user_polygon',geometry:r.geometry};points=toPoints(r.geometry);showForm(r.perceived_class||(r.perception_types||[])[0],r);}
  function showTab(tab){const h=tab==='history';$('#fcu-perception-list').hidden=h;$('#fcu-perception-history').hidden=!h;document.querySelectorAll('[data-tab]').forEach(n=>n.classList.toggle('is-active',n.dataset.tab===tab));}
  function style(r){const k=r.perceived_class||(r.perception_types||[])[0]||'outro';return {color:COLOR[k],weight:r.action_type==='reclassify'?3:2,dashArray:r.action_type==='reclassify'?'7 5':null,fillOpacity:.18};}
  function renderLayers(){layers.clearLayers();layerById.clear();items.filter(r=>r.status!=='archived').forEach(r=>{const k=r.perceived_class||(r.perception_types||[])[0]||'outro';if(!filters.classes.has(k)||!filters.actions.has(r.action_type||'free'))return;const pts=toPoints(r.geometry);if(pts.length<3)return;const l=L.polygon(pts,style(r)).bindTooltip(`Desenho ${drawingId(r.id)} · toque para editar`).on('click',e=>{L.DomEvent.stopPropagation(e);beginGeometryEdit(r);}).addTo(layers);layerById.set(r.id,l);});}
  function card(r,count){const archived=r.status==='archived',k=r.perceived_class||(r.perception_types||[])[0]||'outro',c=document.createElement('article');c.className='fcu-perception-item'+(archived?' is-archived':'');c.innerHTML=`<span class="fcu-card-id">Desenho ${drawingId(r.id)}</span><div class="fcu-item-top"><i style="--fcu-color:${COLOR[k]}"></i><div><strong>${esc(r.title)}</strong><small>${ACTION[r.action_type||'free']} · ${LABEL[k]}</small></div></div><small>${new Date(r.created_at).toLocaleDateString('pt-BR')} · ${count} ${count===1?'versão':'versões'}</small><div class="fcu-perception-item-actions"><button data-view>Ver</button>${archived?'<button data-restore>Restaurar</button>':'<button data-shape>Editar área</button><button data-edit>Editar dados</button><button data-archive>Excluir</button>'}</div>`;c.querySelector('[data-view]').onclick=()=>{const temp=L.polygon(toPoints(r.geometry),style(r));close();const l=layerById.get(r.id)||temp.addTo(map);map.fitBounds(l.getBounds(),{padding:[30,30]});if(!layerById.has(r.id))setTimeout(()=>map.hasLayer(temp)&&map.removeLayer(temp),8000);};if(archived)c.querySelector('[data-restore]').onclick=()=>restore(r.id);else{c.querySelector('[data-shape]').onclick=()=>beginGeometryEdit(r);c.querySelector('[data-edit]').onclick=()=>edit(r);c.querySelector('[data-archive]').onclick=()=>archive(r.id);}return c;}
  async function load(){const list=$('#fcu-perception-list'),history=$('#fcu-perception-history');if(!list)return;if(!user()){items=[];renderLayers();list.innerHTML='<p>Entre para consultar suas percepções.</p>';history.innerHTML='<p>Entre para consultar a Lixeira.</p>';return;}list.innerHTML='<p>Carregando...</p>';const r=await db.from('fcu_perceptions').select('*').order('created_at',{ascending:false});if(r.error){list.innerHTML='<p>Não foi possível carregar suas percepções.</p>';return;}const vr=await db.from('fcu_perception_versions').select('perception_id,version'),counts={};(vr.data||[]).forEach(v=>counts[v.perception_id]=Math.max(counts[v.perception_id]||0,v.version));items=r.data||[];renderLayers();const active=items.filter(x=>x.status!=='archived'),trash=items.filter(x=>x.status==='archived');list.innerHTML=active.length?'':'<p>Você ainda não registrou percepções.</p>';history.innerHTML=trash.length?'':'<p>A lixeira está vazia.</p>';active.forEach(x=>list.appendChild(card(x,counts[x.id]||1)));trash.forEach(x=>history.appendChild(card(x,counts[x.id]||1)));}
  function init(){map=app().map;db=window.PreditorAuth&&window.PreditorAuth.client;if(!map||!db||!build())return false;layers.addTo(map);map.on('click',mapClick);const c=map.getContainer();c.addEventListener('pointerdown',pointerDown,true);c.addEventListener('pointermove',pointerMove,true);c.addEventListener('pointerup',pointerUp,true);db.auth.onAuthStateChange(()=>setTimeout(()=>{load();renderLegendControl();},0));load();setInterval(()=>{const id=String((sample()||{}).id||'');if(id!==lastCell&&$('#fcu-perception-panel').classList.contains('is-open'))renderContext();renderLegendControl();},350);return true;}
  let tries=0;const timer=setInterval(()=>{tries++;if(init()||tries>120)clearInterval(timer);},250);
})();
